package com.consultoriaBuzo.CertificacionIEMS.deshechados;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Luis Alberto
 */
public class VentanaGestionProfesores extends javax.swing.JFrame {

    /**
     * Creates new form GestionProfesores
     */
    public VentanaGestionProfesores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    /*public static void main(String args[]) {
     
    }*/
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoNombre = new javax.swing.JTextField();
        comboBoxAcademia = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBoxTurno = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProfesores = new javax.swing.JTable();
        botonRegistrar = new javax.swing.JButton();
        radioBotonAsesor = new javax.swing.JRadioButton();
        radioBotonDTI = new javax.swing.JRadioButton();
        botonGuardar = new javax.swing.JButton();
        logotipo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mensajeRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoNombre.setToolTipText("");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Academia: ");

        jLabel3.setText("Turno:");

        comboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Matutino", "Vespertino" }));

        tablaProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Academia", "Turno", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaProfesores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaProfesores.setShowGrid(true);
        jScrollPane1.setViewportView(tablaProfesores);
        if (tablaProfesores.getColumnModel().getColumnCount() > 0) {
            tablaProfesores.getColumnModel().getColumn(0).setMinWidth(100);
            tablaProfesores.getColumnModel().getColumn(0).setPreferredWidth(150);
            tablaProfesores.getColumnModel().getColumn(1).setMinWidth(100);
            tablaProfesores.getColumnModel().getColumn(1).setPreferredWidth(150);
            tablaProfesores.getColumnModel().getColumn(2).setMinWidth(20);
            tablaProfesores.getColumnModel().getColumn(2).setPreferredWidth(20);
            tablaProfesores.getColumnModel().getColumn(3).setMinWidth(20);
            tablaProfesores.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        botonRegistrar.setText("Regsitrar");

        radioBotonAsesor.setText("Asesor");

        radioBotonDTI.setText("DTI");

        botonGuardar.setText("Guardar cambios");

        logotipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IEMSLogo.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel5.setText("Gestión de profesores");

        mensajeRegistro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBoxAcademia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 108, Short.MAX_VALUE)
                                .addComponent(comboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textoNombre))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonRegistrar)
                            .addComponent(radioBotonAsesor)
                            .addComponent(radioBotonDTI)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mensajeRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(logotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(botonGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logotipo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(radioBotonDTI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(radioBotonAsesor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensajeRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonGuardar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JComboBox<String> comboBoxAcademia;
    private javax.swing.JComboBox<String> comboBoxTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logotipo;
    private javax.swing.JLabel mensajeRegistro;
    private javax.swing.JRadioButton radioBotonAsesor;
    private javax.swing.JRadioButton radioBotonDTI;
    private javax.swing.JTable tablaProfesores;
    private javax.swing.JTextField textoNombre;
    // End of variables declaration//GEN-END:variables

    /**
     * Regresa el objeto JButton del boton que se usa para guardar
     * @return el JButton para guardar
     */
    public JButton getBotonGuardar() {
        return botonGuardar;
    }

    /**
     * Regresa el objeto JButton del boton que se usa para registrar
     * @return el JButton para registrar
     */
    public JButton getBotonRegistrar() {
        return botonRegistrar;
    }

    /**
     * Regresa el objeto JComboBox de la comboBox que se usa para contener las 
     * academias
     * @return la JComboBox para academias
     */
    public JComboBox<String> getComboBoxAcademia() {
        return comboBoxAcademia;
    }
    
    /**
     * Regresa el objeto JComboBox de la comboBox que se usa para contener los
     * turnos
     * @return la JComboBox para turnos
     */
    public JComboBox<String> getComboBoxTurno() {
        return comboBoxTurno;
    }

    /**
     * Regresa el objeto JRadioButton del radio botón que se usa para seleccionar
     * asesor
     * @return el JRadioButton para asesor
     */
    public JRadioButton getRadioBotonAsesor() {
        return radioBotonAsesor;
    }
    
    /**
     * Regresa el objeto JRadioButton del radio botón que se usa para seleccionar
     * DTI
     * @return el JRadioButton para DTI
     */
    public JRadioButton getRadioBotonDTI() {
        return radioBotonDTI;
    }

    /**
     * Regresa el objeto JTextField de la caja de texto que se usa para introducir
     * el nombre
     * @return el JTextField para el nombre
     */
    public JTextField getTextoNombre() {
        return textoNombre;
    }

    /**
     * Regresa el objeto JTable correspondiente a la tabla en la que se muestran
     * los profesores
     * @return la JTablee de la vista
     */
    public JTable getTablaProfesores() {
        return tablaProfesores;
    }
}
